name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: aayushgid/alumna-backend
  PROJECT_PATH: /home/ubuntu/alumna-llm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
             cd ${{ env.PROJECT_PATH }} &&  restart-docker-compose  
